### ISSUE TITLE
How to generate (or get) BM.npy

### ISSUE THREAD

**Issue by guojiajeremy** [CVRS-Hamlyn/GA-SA-RBF#1]
First, thank you for your great work.

I would like to ask how to get the BM file (BM.npy). They are not existing in the data files provided. There is also no code to generate such files. 

Great thanks!

**Comment by XC9292** [comment]
Hi,

Thanks very much for your interest!

As explained in [GitHub Pages](https://github.com/CVRS-Hamlyn/GA-SA-RBF/tree/main/gen_BM), we use 5 blur metrics to evaluate the quality of pCLE images and average them to generate the final blur metric value.

The code and instructions are also attached in ['here'](https://github.com/CVRS-Hamlyn/GA-SA-RBF/tree/main/gen_BM).

Chi
